Add password command
PRO100BYTE/ne-dos pull request #52
Opened 2023-08-10 05:15 UTC by TheDayG0ne

Генератор паролей

Использование: password [длина], например: password 12
Если аргумент не задан, будет сгенерирован пароль из 8 символов

2023-08-11 16:17 UTC, mraliscoder requested changes
Пароль из 12-16 символов лучше, 8 символов не так безопасно. + Math.random() не криптобезопасная функция, не апрув

2023-08-11 16:20 UTC, TheDayG0ne commented
хм, насчет криптобезопасности подумаю

2023-08-11 16:22 UTC, mraliscoder commented
https://stackoverflow.com/questions/9719570/generate-random-password-string-with-requirements-in-javascript

2023-08-11 16:22 UTC, mraliscoder commented
самый верхний ответ в прошлой ссылке не смотреть, он не безопасен \
вот там где js-crypto можно глянуть

2023-08-12 13:51 UTC, TheDayG0ne commented
ревью плз

2023-08-12 13:53 UTC, mraliscoder approved these changes
теперь апрув

2023-08-12 13:53 UTC, TheDayG0ne commented
ура :)))))

2023-08-12 13:57 UTC, merged