Add base64 command
PRO100BYTE/ne-dos pull request #53
Opened 2023-08-11 10:29 UTC by TheDayG0ne

Добавление команды для кодирования текста с помощью base64

2023-08-11 16:16 UTC, mraliscoder requested changes
Не помешало бы так:

`base64 encode <text>` - encode \
`base64 decode <base64>` - decode (image or file will open in new tab)

2023-08-11 16:16 UTC, mraliscoder commented on src/commands/Utility/base64.js
> +        term.writeln(`${encoded}`);
`term.writeln(encoded)`

2023-08-11 16:19 UTC, TheDayG0ne commented
я думал decode вынести в отдельную команду, debase64

2023-08-11 16:19 UTC, mraliscoder commented
не, хрень решение

2023-08-11 16:20 UTC, TheDayG0ne commented
тогда перепишу команду

2023-08-12 10:18 UTC, TheDayG0ne commented
review

2023-08-12 13:54 UTC, mraliscoder approved these changes

2023-08-12 13:55 UTC, merged